Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.Build.Framework;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;

namespace Final_Project.Models
{
	public class Order
	{
		
		public int OrderId { get; set; }
		[Required]
		public string PosterName { get; set; }
		[Required]
        [RegularExpression(@"^\d{11}$", ErrorMessage = "Please enter a valid 11-digit phone number.")]
        public string Phone { get; set; }
		[Required]
		public string mail { get; set; }
		[Required]
		public string? Address { get; set; }
		public string? UserName { get; set; }

		public string? ServiceType { get; set; }
		[ForeignKey("TaskPoster")]
		public int TaskPosterId { get; set; }
		[ForeignKey("Task")]
		public int TaskId { get; set; }
		public virtual Task? Task { get; set; }
		
		public virtual TaskPoster? TaskPoster { get; set; }

	}
}

Controllers/OrderController.cs
using Final_Project.Models;
using Final_Project.Reprosatory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NuGet.Protocol.Core.Types;
using Task = Final_Project.Models.Task;

namespace Final_Project.Controllers
{
	public class OrderController : Controller
	{
		LaborShare context;
		IOrderRepo OrederRepo;
		public OrderController(LaborShare _laborShare,IOrderRepo _orederRepo)
		{
			context = _laborShare;
			OrederRepo = _orederRepo;
		}
		public IActionResult Index()
		{
			
			return View();
		}
        [Authorize]
        public IActionResult AskService()
		{
			List<Task> taskList = context.Tasks.ToList();
			ViewData["tasks"] = taskList;
			return View();
		}
        [Authorize]
        public IActionResult SelectedAsk()
		{
			string serviceType = Request.Query["seviceType"];
			ViewData["serviceType"] = serviceType;
			List<Task> taskList = context.Tasks.ToList();
			ViewData["tasks"] = taskList;
			return View();
		}
		[HttpPost]
        [Authorize]
        public IActionResult AskService(Order NewOrder)
		{
			if (ModelState.IsValid == true)
			{
				NewOrder.TaskPosterId = 1;
				NewOrder.TaskId = 1;
				
				context.Orders.Add(NewOrder);
				context.SaveChanges();
				
				return RedirectToAction("Index");
			}
			
			List<Task> taskList = context.Tasks.ToList();
			ViewData["tasks"] = taskList;
			return View( NewOrder);
		}
        [Authorize]
        public IActionResult ShowOrders()
		{
			//List<Order> OrderList = OrederRepo.Getall();
			
			List<Order> OrderList = context.Orders.Where(o=>o.UserName==User.Identity.Name).ToList();


			return View(OrderList);
		}
        [Authorize]
        public IActionResult DeleteOrder(int id)
		{
			Order orderToDelete = OrederRepo.GetById(id);
			if (orderToDelete != null)
			{
				OrederRepo.Remove(orderToDelete);
				return View(orderToDelete);

			}
            return RedirectToAction("ShowOrders");
        }
		public IActionResult EditOrder(int id)
		{
			Order order= OrederRepo.GetById(id);
			if (order != null)
			{
                List<Task> taskList = context.Tasks.ToList();
                ViewData["tasks"] = taskList;
                return View(order);
			}
			return RedirectToAction("ShowOrders");
		}
		[HttpPost]
		[Authorize]
		public IActionResult EditOrder([FromRoute] int id,Order order)
		{
			if (order != null) 
			{
				
				OrederRepo.Update(id,order);
				context.SaveChanges();
			}
			return RedirectToAction("ShowOrders");
		}


	}
}

Views/Order/AskService.cshtml
@model Order
@{
    ViewData["Title"] = "AskService";
	Layout = "_PageWithNavLayout";
	SelectList taskOptions = new SelectList(ViewBag.tasks, "Title", "Title");

}

<h1 style="width:40%; margin:0 auto;margin-top:30px">Choose Your Service</h1>
<br />



<form method="post" asp-action="AskService" asp-controller="Order" style="width:40%; margin:0 auto;">
	<div>
		<label asp-for="PosterName">Enter Your Name</label>
		<input asp-for="PosterName" class="form-control" />
		<span asp-validation-for="PosterName" class="text-danger" />
		
	</div>
	<div>

		<label asp-for="Phone">Enter Your Phone Number</label>
		<input asp-for="Phone" class="form-control" />
		<span asp-validation-for="Phone" class="text-danger" />
		
	</div>

	<div>
		<label asp-for="Address">Enter Your Address</label>
		<input asp-for="Address" class="form-control" />
		<span asp-validation-for="Address" class="text-danger" />
		
	</div>
	<div>
		<label asp-for="mail">Enter Your Mail</label>
		<input asp-for="mail" class="form-control" />
		<span asp-validation-for="mail" class="text-danger" />

	</div>
	<div>
		<input asp-for="UserName" type="hidden" value="@User.Identity.Name" class="form-control" />

	</div>
	<div>
		<label asp-for="ServiceType">Select Your Service</label>
		<select asp-for="ServiceType" asp-items="taskOptions" class="form-control" >
			<option value="">Select a Service</option>
		</select>
		<span asp-validation-for="ServiceType" class="text-danger" />
	</div>
	
	<br />
	<input type="submit" class="btn btn-primary" value="Ask" />
	<a href="/Task/ShowAllServices" class="btn btn-primary">Cancel</a>

</form>
@section scripts{
	<script src="~/lib//jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
	
}

Views/Order/DeleteOrder.cshtml
@{
    ViewData["Title"] = "DeleteOrder";
    Layout = "_PageWithNavLayout";
}


<div style="display: flex; justify-content: center; align-items: center; height: 20vh;">

    <h1>Your Order Deleted Successfully</h1>


</div>
<div style="display: flex; justify-content: center; align-items: center; height: 5vh;">

    <a style="margin-right:30px" href="/Order/ShowOrders" class="btn btn-primary">Show my orders</a>
    <a href="/Order/ShowOrders" class="btn btn-primary">Back</a>

</div>

Views/Order/EditOrder.cshtml
@model Order
@{
    ViewData["Title"] = "EditOrder";
	Layout = "_PageWithNavLayout";
	SelectList taskOptions = new SelectList(ViewBag.tasks, "Title", "Title");
}

<h1 style="width:40%; margin:0 auto;">Select a Service</h1>

<form method="post" action="/Order/EditOrder/@Model.OrderId" style="width:40%; margin:0 auto;">
	<div>
		<label asp-for="PosterName">Enter Your Name</label>
		<input asp-for="PosterName" class="form-control" />
		<span asp-validation-for="PosterName" class="text-danger" />

	</div>
	<div>

		<label asp-for="Phone">Enter Your Phone Number</label>
		<input asp-for="Phone" class="form-control" />
		<span asp-validation-for="Phone" class="text-danger" />

	</div>

	<div>
		<label asp-for="Address">Enter Your Address</label>
		<input asp-for="Address" class="form-control" />
		<span asp-validation-for="Address" class="text-danger" />

	</div>
	<div>
		<label asp-for="mail">Enter Your Mail</label>
		<input asp-for="mail" class="form-control" />
		<span asp-validation-for="mail" class="text-danger" />

	</div>
	<div>
		<input asp-for="UserName" type="hidden" value="@User.Identity.Name" class="form-control" />

	</div>
	<div>
		<label asp-for="ServiceType">Select Your Service</label>
		<select asp-for="ServiceType" asp-items="taskOptions" class="form-control">
			<option value="">Select a Service</option>
		</select>
		<span asp-validation-for="ServiceType" class="text-danger" />
	</div>
	@*<div>
		<input type="hidden" name="OrderId" value="@Model.OrderId">

	</div>*@

	<br />
	<input type="submit" class="btn btn-primary" value="Apply" />
	<a href="/Task/ShowAllServices" class="btn btn-primary">Cancel</a>

</form>
@section scripts{
	<script src="~/lib//jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

Views/Order/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "_PageWithNavLayout";
}
<div style="display: flex; justify-content: center; align-items: center; height: 20vh;">

    <h1 >Your Order Sent Successfully</h1>
   

</div>
<div style="display: flex; justify-content: center; align-items: center; height: 5vh;">

    <a style="margin-right:30px" href="/Order/ShowOrders" class="btn btn-primary">Show my orders</a>
    <a href="/Order/AskService" class="btn btn-primary">Back</a>

</div>
   

Views/Order/SelectedAsk.cshtml
@{
    ViewData["Title"] = "SelectedAsk";
	Layout = "_PageWithNavLayout";
}

<h1 style="width:500px;margin:0 auto;margin-top:40px">@ViewData["serviceType"]</h1>
@model Order

<form method="post" asp-action="AskService" asp-controller="Order" style="width:40%; margin:0 auto;">
	<div>
		<label asp-for="PosterName">Enter Your Name</label>
		<input asp-for="PosterName" class="form-control" />
		<span asp-validation-for="PosterName" class="text-danger" />

	</div>
	<div>

		<label asp-for="Phone">Enter Your Phone Number</label>
		<input asp-for="Phone" class="form-control" />
		<span asp-validation-for="Phone" class="text-danger" />

	</div>

	<div>
		<label asp-for="Address">Enter Your Address</label>
		<input asp-for="Address" class="form-control" />
		<span asp-validation-for="Address" class="text-danger" />

	</div>
	<div>
		<label asp-for="mail">Enter Your mail</label>
		<input asp-for="mail" class="form-control" />
		<span asp-validation-for="mail" class="text-danger" />

	</div>
	<div>
		<input asp-for="ServiceType" type="hidden" value="@ViewBag.serviceType" />
	</div>
	<div>
		<input asp-for="UserName" type="hidden" value="@User.Identity.Name" class="form-control" />

	</div>

	<br />
	<input type="submit" class="btn btn-primary" value="Ask" />
	<a href="/Task/ShowAllServices" class="btn btn-primary">Cancel</a>

</form>
@section scripts{
	<script src="~/lib//jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

}

Views/Order/ShowOrders.cshtml
@{
    ViewData["Title"] = "ShowOrders";
	Layout = "_PageWithNavLayout";

}
@model List<Order>


    <div class="container mt-3">
    <h2 style ="width:40%; margin:0 auto;margin-top:30px">
        Your Pinned Services</h2>
        <br />
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>Service Type</th>
                    <th></th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
            @foreach (Order item in Model)
            {
                <tr>
                    <td>@item.PosterName</td>
                    <td>@item.Address</td>
                    <td>@item.Phone</td>
                    <td>@item.ServiceType</td>
                    <td><a class="btn btn-warning" href="/Order/EditOrder?id=@item.OrderId">Edit</a></td>
                    <td><a id="cancel" onclick="handleCancelClick(event)" class="btn btn-warning" href="/Order/DeleteOrder?id=@item.OrderId" data-order-id="@item.OrderId">Cancel</a></td>
                </tr>
            }
                
            </tbody>
        </table>
    </div>
<a href="/Task/ShowAllServices" class="btn btn-outline-success" style="width:200px;margin:0 auto;">Back</a>

@section Scripts {
   @* <script>
        var cancel= document.getElementById("cancel");
        cancel.addEventListener("click",function (e){
            window.prompt
        })
    </script>*@
    <script>
       
        function handleCancelClick(e) {
            e.preventDefault();
            var confirmed = window.confirm("Are you sure you want to cancel?");

            if (confirmed) {
                // Add any code here that should run if the user confirms the cancellation
                var id = e.target.dataset.orderId;
                window.location.href = e.target.href;
            }
        }
        
        
    </script>
}
   